#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class Mapped:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'minimum_order': 'int',
            'name': 'str',
            'AvailableModifiers': 'list[Availablemodifier]',
            'maximum_order': 'int',
            'category_id': 'int',
            'description': 'str'

        }


        #Minimum Number of Modifiers to Order
        self.minimum_order = None # int
        #Category Name
        self.name = None # str
        self.AvailableModifiers = None # list[Availablemodifier]
        #Maximum Number of Modifiers to Order
        self.maximum_order = None # int
        #Category ID
        self.category_id = None # int
        #Category Description
        self.description = None # str
        
