#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class POSCategory:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'pos_category_parent_id': 'int',
            'pos_category_name': 'str',
            'items': 'list[POSMenuItemDetail]',
            'pos_category_id': 'int',
            'instructional_text': 'str',
            'allow_order': 'bool'

        }


        #Category Parent ID
        self.pos_category_parent_id = None # int
        #POS Category Name
        self.pos_category_name = None # str
        self.items = None # list[POSMenuItemDetail]
        #POS Category ID
        self.pos_category_id = None # int
        #Instructional Text
        self.instructional_text = None # str
        #Category allows orders
        self.allow_order = None # bool
        
