#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class PreAuthPayment:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'status': 'int',
            'tip_amount': 'float',
            'total_amount': 'float',
            'amount_before_tip': 'float',
            'payment_source': 'str',
            'external_payment_id': 'int',
            'external_response_field_1': 'str',
            'tender_type_name': 'str',
            'external_response_field_2': 'str',
            'external_response_field_3': 'str',
            'external_response_field_4': 'str'

        }


        #Payment Status
        self.status = None # int
        #Payment tip amount
        self.tip_amount = None # float
        #Payment Total Amount
        self.total_amount = None # float
        #Payment amount before tip
        self.amount_before_tip = None # float
        #Payment Source
        self.payment_source = None # str
        #SubtleData External Payment ID
        self.external_payment_id = None # int
        #External Data 1
        self.external_response_field_1 = None # str
        #Tender Type
        self.tender_type_name = None # str
        #External Data 2
        self.external_response_field_2 = None # str
        #External Data 3
        self.external_response_field_3 = None # str
        #External Data 4
        self.external_response_field_4 = None # str
        
