#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class PreAuthCard:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'card_type': 'str',
            'expiration_year': 'str',
            'tender_name': 'str',
            'expiration_month': 'str',
            'credit_card_id': 'int',
            'nickname': 'str',
            'last_4_digits': 'str'

        }


        #Credit Card Type
        self.card_type = None # str
        #Expiration Year
        self.expiration_year = None # str
        #Name on Tender
        self.tender_name = None # str
        #Expiration Month
        self.expiration_month = None # str
        #SubtleData Credit Card ID
        self.credit_card_id = None # int
        #Credit Card Nickname
        self.nickname = None # str
        #Last 4 Digits on Card
        self.last_4_digits = None # str
        
